[FileDialog]
history=file:///home/ati, file:///home/ati/Downloads, file:///home/ati/Downloads/Books, file:///home/ati/Downloads/Books/jjjj, file:///home/ati/Attia-Pro/Turboard-E-kalite/photos, file:///home/ati/Attia-Pro/Turboard-E-kalite/sounds
lastVisited=file:///home/ati/Attia-Pro/Turboard-E-kalite/sounds
qtVersion=5.15.17
shortcuts=file:, file:///home/ati
sidebarWidth=91
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\xc6\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0X\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xea\0\0\0\x1\0\0\0\0\0\0\0:\0\0\0\x1\0\0\0\0\0\0\0<\0\0\0\x1\0\0\0\0\0\0\0\x66\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff)
viewMode=Detail
