-- autocmds are automatically loaded on the verylazy event
-- default autocmds that are always set: https://github.com/lazyvim/lazyvim/blob/main/lua/lazyvim/config/autocmds.lua
-- add any additional autocmds here
-- local m = {}
--
-- function m.cowboy()
--   ---@type table?
--   local id
--   local ok = true
--   for _, key in ipairs({ "h", "j", "k", "l", "+" }) do
--     local count = 0
--     local timer = vim.loop.new_timer()
--     vim.keymap.set("n", key, function()
--       if vim.v.count > 0 then
--         count = 0
--       end
--       if count >= 20 then
--         ok, id = pcall(vim.notify, "daddy, chill.", vim.log.levels.warn, {
--           icon = "🫠",
--           replace = id,
--           keep = function()
--             return count >= 10
--           end,
--         })
--         if not ok then
--           id = nil
--           return key
--         end
--       else
--         count = count + 1
--         timer:start(2000, 0, function()
--           count = 0
--         end)
--         -- return the key to maintain the original key mapping behavior
--         return key
--       end
--     end, { expr = true, silent = true })
--   end
-- end
--
-- return m
